version: '3'

services:
  database: 
    image: mysql:8.0
    container_name: diffusion-database
    restart: always
    volumes:
      - /diffusion/database
      - ./src/database/mysql/init:/docker-entrypoint-initdb.d/
      - ./src/database/mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  api:
    build: .
    container_name: diffusion-api
    depends_on:
      - database
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=database
      - MYSQL_DATABASE=diffusion
      - MYSQL_PORT=3306
    ports:
      - 3001:3001
    volumes:
      - ./:/diffusion/api
      - /diffusion/api/node_modules
